name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Clean npm cache
        run: npm cache clean --force
        working-directory: ./Portfolio-app

      - name: Install dependencies
        run: npm install
        working-directory: ./Portfolio-app

      - name: Make vite executable
        run: chmod +x node_modules/.bin/vite
        working-directory: ./Portfolio-app

      - name: Build project
        run: npm run build
        working-directory: ./Portfolio-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./Portfolio-app/dist
